### ISSUE TITLE
 mdy("04 July 2019") GIVES  "2019-04-20" : Instead should give an error. 

### ISSUE THREAD

**Issue by gunawebs** [tidyverse/lubridate#1164]
Brief description of the problem:

 mdy("04 July 2019") GIVES  "2019-04-20" : Instead should give an error. 

```r
mdy("04 July 2019")
```
Output is: [1] "2019-04-20"

Which is WRONG

**Comment by vspinu** [comment]
Hi @gunawebs! I see it might be confusing, but you are asking for `mdy` month-day-year and you get 042019 parsed as 04-20-2019. 

Lubridate's parser is a bit too lax trying to accommodate way to many patterns at once, so you get such un-intended situation.

If guess your use case is has to do with heterogeneous date formats, so you would like to error on unexpected formats, then you should be using the fine-control `parse_date_time` with `Y` format instead of `y`, or explicit formats:


```
parse_date_time(c("04 July 2019", "July 04 2019"), "mdY")
# [1] NA               "2019-07-04 UTC"
# Warning message:
#  1 failed to parse. 
parse_date_time(c("04 July 2019", "July 04 2019"), "%m %d %Y", exact=TRUE)
# [1] NA               "2019-07-04 UTC"
# Warning message:
#  1 failed to parse. 


parse_date_time(c("04 July 2019", "July 04 2019"), c("dmY", "mdY"))
# [1] "2019-07-04 UTC" "2019-07-04 UTC"
parse_date_time(c("04 July 2019", "July 04 2019"), c("%d %m %Y", "%m %d %Y"), exact=TRUE)
# [1] "2019-07-04 UTC" "2019-07-04 UTC"  
```
