### ISSUE TITLE
Set time zone with hour shift format

### ISSUE THREAD

**Issue by qutang** [tidyverse/lubridate#332]
For example:

To set time zone to "America/New_York", the accepted time zone string could be in the hour shift format like "M0500" or "-05:00", depending on the daylight saving, it could also be "M0400" or "04:00".

**Comment by vspinu** [comment]
Why M in `M0500`? If anything it should be `Z0500` as in Zulu ts indicator in ISO8601:

```
> ymd_hms("2015-07-02 12:51:58Z-04:00")
[1] "2015-07-02 16:51:58 UTC"
```

**Comment by qutang** [comment]
Yes, better go with the standard, just reviewed the standard.
I would say if you can add support like:
```
ts = here()
force_tz(ts) = "-0400" or force_tz(ts) = "-04:00" (meaning time zone shift from current time zone)
force_tz(ts) = "Z-04:00" (meaning time zone shift from UTC)
```
`Z` would just means UTC time. 
Same with `with_tz` and `tz`.

This is very helpful as in my work we often just record the shift (easy to parse as numbers) instead of the name of the time zones.

Also a tiny utility function to convert between name of time zone and the shift could also be useful sometimes.

Excellent work on the package, I like it a lot.

**Comment by vspinu** [comment]
If your offsets are recorded separately you can use `hm` parsing function like in:

```
now() - hm("04:00")
```

Unfortunately `hm` and `hms` don't recognize negative offsets. I have opened an #333 specifically for this.

**Comment by qutang** [comment]
Looks great. I'm not sure if involving these to force_tz and with_tz provides a more clean interface.

**Comment by vspinu** [comment]
On the second look this issue is not well defined. There is no mapping between offsets and actual time zones because time zones are geo-political constructs with irregular historical definitions. So guessing the actual time-zone from an offset is not an option. 

Using fixed offsets for conversion is meaningful though, but  a well defined use case remains to be seen.  Any R function that operates with offsets must _not_ return a vector with non-standard `tzone` attribute because all other tools in R wouldn't understand it. So the use of such offsets is bound to be for internal purpose only and, thus of limited reach.

**Comment by kenahoo** [comment]
My timezone database (in Mac OS 10.15) has fixed-offset zones, is that not standard?

```
% ls /usr/share/zoneinfo/Etc/
GMT		GMT+11		GMT+4		GMT+8		GMT-10		GMT-14		GMT-5		GMT-9		UTC
GMT+0		GMT+12		GMT+5		GMT+9		GMT-11		GMT-2		GMT-6		GMT0		Universal
GMT+1		GMT+2		GMT+6		GMT-0		GMT-12		GMT-3		GMT-7		Greenwich	Zulu
GMT+10		GMT+3		GMT+7		GMT-1		GMT-13		GMT-4		GMT-8		UCT
```
