### ISSUE TITLE
Feature request: Would be great to have a function that checks a vector of dates for missing days

### ISSUE THREAD

**Issue by kendonB** [tidyverse/lubridate#334]
All in the title.

**Comment by vspinu** [comment]
> All in the title

Please  give an example. What do you mean by "missing  days"?

**Comment by kendonB** [comment]
This is very hacky, but the function would have functionality like this for data.frames (which I imagine would be its primary use case), and something similar for date vectors. Could be generalized to handle weekly/monthly/annual data.

    dates <- seq(as.Date("2011-01-01"), as.Date("2011-12-31"), by = "day")
    var1 <- rnorm(length(dates))
    var2 <- rnorm(length(dates))
    df <- data.frame(day = dates, var1 = var1, var2 = var2)
    df <- df[-100, ]
    
    fill_missing <- function(df, date_var) {
      first_date <- min(df[, date_var])
      last_date <- max(df[, date_var])
      all_dates <- seq(first_date, last_date, by = "day")
      missing_dates <- all_dates[!(all_dates %in% df[, date_var])]
      if (length(missing_dates) > 0){
        new_rows <- df[1:length(missing_dates), ]
        new_rows[,] <- NA
        new_rows[, date_var] <- missing_dates
        df <- rbind(df, new_rows)
      }
      df[order(df[, date_var]),]
    }
  
    df_new <- fill_missing(df, "day")
    df_new[100, ]
    3651 2011-04-10   NA   NA

**Comment by ptoche** [comment]
What a coincidence, I am writing a hack for something a bit like this. Explanation: firms distribute dividends whenever they feel like it, some quarterly, some biannually, some rarely, and at dates they select, with the result that if a firm distributes, say, quarterly dividends from 1980-1990, then none from 1991-1999, and then again from 2000-2010. One natural approach to this problem is to create a set of quarterly dates on 1991-1999 and set dividends to zero for every quarter on that range. A function that would create missing dates would help, but it would need to have some flexibility.  

Filling every missing day and setting dividends to zero on those days would be misleading. In this case, we want to fill the missing quarters, not every missing day. In other examples, one may want to fill only missing "business days" or trimester dates or semi-annual dates. Also being able to input a vector of manually-set dates would be useful.

Perhaps something like this already exists, but I couldn't find it. And hacking dates is a real pain!

**Comment by hadley** [comment]
I think this is outside of the scope of lubridate; you can use lubridate to generate the sequence of full dates and then use `%in%` or similar to determine which dates are missing from your sequence.
