### ISSUE TITLE
round_date for timespan classes

### ISSUE THREAD

**Issue by blongworth** [tidyverse/lubridate#500]
I'd like to be able to round timespans and/or periods, but round_date calls `round.POSIXt()` which in turn calls `as.POSIXct()`, which fails to convert period objects. Would this require adding a `round_period` function in lubridate, or am I missing something?

`round_date(Sys.time() - (Sys.time() - 5000))`

returns:

`Error in as.POSIXct.default(x) : 
  do not know how to convert 'x' to class “POSIXct”`

**Comment by vspinu** [comment]
In your example it's a `difftime` object which is essentially a number. You can use `round` on it:

```r
round(Sys.time() - (Sys.time() - 5000))
```

For lubridate's time spans (`periods`, `intervals`, and `durations`) one would need a separate method for `round_date` or even better a new function `round_timespan` because those are not representing instants.
