### ISSUE TITLE
dmy chooses arbitrary number of elements to decide if there's a format

### ISSUE THREAD

**Issue by azeloc** [tidyverse/lubridate#569]
Consider the following vectors: 

```
dates_vector_1 <- c("22/08/2016","29/08/2016","05/09/2016","12/09/2016")
dates_vector_2 <- c(rep("1", 500), dates_vector_1)
dates_vector_3 <- c(rep("1", 800), dates_vector_1)
```

`dmy` fails to detect formats on the third, even though it's capable of finding it on the second.

```
library(lubridate)

dmy(dates_vector_1)
dmy(dates_vector_2)
dmy(dates_vector_3)
```

Is this supposed to happen? If it is, why?

**Comment by vspinu** [comment]
This is a consequence of guessing formats based on a deterministic sub-sample of the original vector. This issue was aleviated somewhat recently, but it's impossible to solve efficiently without dropping format guesser to C level. Not something which I would consider in the future.    

See #307 #308. You can disable guesser with `parse_date_time` and `train=FALSE`.

**Comment by azeloc** [comment]
I got the same behavior. Am i doing anything wrong?

```
parse_date_time(dates_vector_1, train = T, orders = 'dmy')
parse_date_time(dates_vector_3, train = T, orders = 'dmy')
```

**Comment by vspinu** [comment]
> Am i doing anything wrong?

Not really, it's just that your date-time vector is too sparse and there is not a single valid input found among pseudo-random subset of your dates. Please use either `exact=TRUE` or `parse_date_time2` to disallow guessing.
