### ISSUE TITLE
Solaris CRAN test error

### ISSUE THREAD

**Issue by wlandau** [tidyverse/lubridate#575]
See the [log for version 1.6.0](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/lubridate-00check.html). Possibly related: #574.

**Comment by vspinu** [comment]
Not sure how I can fix this without access to solaris.  My current bandwidth doesn't allow me to target that platform, sorry.  

It's almost surely  unrelated to #574.

**Comment by vspinu** [comment]
The above was fixed in 1.7.0 but there is one new issue related to time zones. We are now relying on time-zone manipulation and it looks like CCTZ cannot find zoneinfo on that platform.  User can fix it by setting the `TZDIR` environment on that platform. I could also try setting it on lubridate's startup if it's not set.

**Comment by vspinu** [comment]
Actually I am already setting TZDIR on windows:) Will fix this for the next release.
