### ISSUE TITLE
as_date no longer supports argument "format"

### ISSUE THREAD

**Issue by ian-price** [tidyverse/lubridate#607]
Between versions 1.6.0 and 1.7.1, the function as_date lost the ability to use the argument "format".  I was using this when the date was embedded in part of the text.
the command
```
as_date(MY_INPUT, format = "MY_TEXT_%Y%m%d") 
```
returns an error in 1.7.1
```
Error in .local(x, ...) : unused argument (format = "MY_TEXT_%Y%m%d")
```

**Comment by vspinu** [comment]
Well, technically format argument was never part of the API, and it worked for character vectors because in 1.6.0 it did as.Date. In 1.7.0 a range of issues with character parsing were fixed (#598, #597, #536) and that means no `format` argument can no work. Sorry about that. You can use any of the available parser functions in lubridate - `parse_date_time`, `parse_date_time2` or `fast_strptime`. 

On your string, the simplest `ymd(MY_INPUT)` should work.

**Comment by ian-price** [comment]
Thanks for the quick response. For my needs, I replaced it with as.Date, so I'm fine. Thank you for the other suggestions.
I just wanted to report the change in functionality as I never know whether a change like this is intended or a side-effect. Sounds like it's intended, so I'll close the issue.

**Comment by vspinu** [comment]
as_date is advertised as drop-in replacement for as.Date. I will try to fix this.

**Comment by huftis** [comment]
Note that `as_datetime()` is *also* advertised as a drop-in replacement for `as.POSIXct()`, but doesn’t support the `format` argument, which `as.POSIXct()` does. But wouldn’t it be cleaner to have `as_date()` and `as_datetime()` *not* support the `format` argument (i.e. the current behaviour)? If people want to parse characters as dates or datetimes, they can easily use `parse_date()` and `parse_datetime()`, which *does* support a `format` argument, and which *are* drop-in replacements for `as.Date()` and `as.POSIXct()`.

**Comment by vspinu** [comment]
`parse_date` and `parse_datetime` are not part of lubridate. In any case, parsers are not drop-ins for as.Date because they work on strings only. 

I think, the best is to leave format argument to character methods as before. The issues is that lubridate parsers are not equivalent to strptime and one would need to treat this particular case specially and redirect it to strptime internally. This is how I plan to fix this at the moment.

**Comment by BastienFR** [comment]
The argument `format` should be remove from the help file if it's not used anymore.  In my case, with lubridate_1.7.2, `?as_date` gives a page with `format`.  It's very confusing.

**Comment by vspinu** [comment]
It is supported.

**Comment by BastienFR** [comment]
Humm....  I feel bad now, it was a bug on my side, sending a numeric vector (for which format isn't supported, which makes sense) vs a character vector for which it is...  my bad, sorry
