### ISSUE TITLE
Vectorization with incorrectly formatted dates fails for long vectors

### ISSUE THREAD

**Issue by vkostyuk** [tidyverse/lubridate#652]
For a "short" vector, `ymd()` works as expected:
```
> dates <- c(rep("05/06/2000", 3000), rep("2000-05-06", 5))
> tail(ymd(dates))
[1] NA           "2000-05-06" "2000-05-06" "2000-05-06" "2000-05-06" "2000-05-06"
Warning message:
 3000 failed to parse.
```
For "long" vectors, it fails:
```
> dates <- c(rep("05/06/2000", 30000), rep("2000-05-06", 5))
> tail(ymd(dates))
[1] NA NA NA NA NA NA
Warning message:
All formats failed to parse. No formats found. 
```
Expected result: last five dates correctly parsed.

**Comment by cderv** [comment]
When you are using `ymd`, you are using the guessing mechanism of lubridate for the format to parse with (like `%Y-%m-%d`). The guessing mechanism is based on a subset of the input. You don't get the correct result because in the long vectors case, there is none of the 5 last trailing dates in the subset guessing vectors. Whereas, in the short one you get **one** of the 5 trainling dates in the vector used for guessing format. 

If you do not use this guessing mechanism with `parse_date_time` and `exact = TRUE`, it works fine.
``` r
library(lubridate)
#> 
#> Attachement du package : 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
dates <- c(rep("05/06/2000", 30000), rep("2000-05-06", 5))
tail(parse_date_time(dates, "%Y-%m-%d", exact = TRUE))
#> [1] NA               "2000-05-06 UTC" "2000-05-06 UTC" "2000-05-06 UTC"
#> [5] "2000-05-06 UTC" "2000-05-06 UTC"
```

I think your example is an edge one and not sure the guessing mechanism of lubridate should cover this.
There is some discussion on the guesser in #308, #516.

The guesser mechanism is explained in [`help("parse_date_time")`](https://www.rdocumentation.org/packages/lubridate/versions/1.7.3/topics/parse_date_time). 
You shoud use `exact=TRUE` like above or `fast_strptime` or `parse_datetime2`. Or another parsing function from base like `strptime`, or the 📦 `anytime`.

**Comment by vkostyuk** [comment]
I see, thanks @cderv . The documentation for `ymd` (i.e., `?ymd`) should spell out this limitation but does not.

**Comment by vspinu** [comment]
I have added more pointers to `ymd` and `ymd_hms` docs.
