### ISSUE TITLE
Deprecate `milliseconds()`, `microseconds()` etc

### ISSUE THREAD

**Issue by hadley** [tidyverse/lubridate#706]
IMO they clutter the api for little gain - is `millseconds(1)` really more expressive than `seconds(1e-3)`?

**Comment by doorisajar** [comment]
I found this issue when trying to use these functions. A common paradigm in REST APIs is to submit timestamps by milliseconds since some origin, but I noticed when trying to use `milliseconds` for this purpose that [the sub-second functions appear to do the math backwards](https://github.com/tidyverse/lubridate/blob/455a759d34e292df9b6e45bd4c888851ff94fb5e/R/periods.r#L490
):

```
milliseconds <- function(x = 1) seconds(x/1000)
microseconds <- function(x = 1) seconds(x/1000000)
nanoseconds <- function(x = 1) seconds(x/1e9)
picoseconds <- function(x = 1) seconds(x/1e12)
```

AFAICT, all of those `\` should be `*`:

```
library(lubridate)

as.numeric(interval(as.Date(origin), ymd("2019-01-01"))) * 1e3
#> [1] 1.546301e+12
as.numeric(seconds(interval(as.Date(origin), ymd("2019-01-01")))) * 1e3
#> [1] 1.546301e+12
as.numeric(milliseconds(interval(as.Date(origin), ymd("2019-01-01"))))
#> [1] 1546301
```

 I can do a PR for it, but if you'd prefer to remove them, then I won't go to the unnecessary effort. :)

**Comment by kenahoo** [comment]
Personally I do think the functions should stay, because I think `milliseconds(33)` and `nanoseconds(400)` are much clearer and less error-prone than `seconds(33e-3)` and `seconds(400e-9)`.

**Comment by doorisajar** [comment]
Oh, they work as documented, I'm misusing them. It would be nice to have something that does what I was trying to do (find out how many milliseconds long some interval is), but I guess that's a different use case.

**Comment by vspinu** [comment]
@doorisajar you can compute the length of intervals (or other time spans) with `time_length`. The lowest unit is second though. 

@hadley Regarding the OP I also think it's better to keep them as they are old and probably used in the external code. Also I do agree with @kenahoo that they are cleaner semantically. Feel free to re-open if you disagree.

**Comment by hadley** [comment]
Yeah, I don't feel particularly strongly about this.
