### ISSUE TITLE
`dmy` function fails to parse Sept as September

### ISSUE THREAD

**Issue by metanoid** [tidyverse/lubridate#722]
It seems that the `dmy` function "understands" that "Sep" is an abbreviation of "September", but not that "Sept" is also an abbreviation for "September".

```r
dmy("1 Sep 2018")
# "2018-09-01"
dmy("1 Sept 2018")
# NA
# Warning message:
# All formats failed to parse. No formats found. 
```

For reference, I'm using these settings:
```r
Sys.getlocale("LC_TIME")
# "English_United States.1252"
```

**Comment by cderv** [comment]
I wanted to help the investigation. This is what I found. 
``` r
library(lubridate, warn.conflicts = FALSE)
# to have the same locale
Sys.setlocale("LC_TIME", "English")
#> [1] "English_United States.1252"
# with abbreviation Sep, both are working
parse_date_time("1 Sep 2018", "dbY")
#> [1] "2018-09-01 UTC"
parse_date_time2("1 Sep 2018", "dbY")
#> [1] "2018-09-01 UTC"
# with abbreviation Sept, the lubridate guessing mechanism is lost
parse_date_time("1 Sept 2018", "dbY")
#> Warning: All formats failed to parse. No formats found.
#> [1] NA
parse_date_time2("1 Sept 2018", "dbY")
#> [1] "2018-09-01 UTC"
```

Abreviation *Sept* for *September* is not recognized for this local. Only *Sep* or *Sep.*
Let's dig into guessing mechanism.

``` r
guess_formats("1 Sep 2018", "dbY")
#>        dObY         dbY 
#> "%d %Ob %Y"  "%d %b %Y"
guess_formats("1 Sep. 2018", "dbY")
#>         dObY          dbY 
#> "%d %Ob. %Y"  "%d %b. %Y"
guess_formats("1 Sept 2018", "dbY")
#> NULL
```

Internally, regex are used to match the format

``` r
loc_reg <- lubridate:::.get_locale_regs()
flex_regs <- c(loc_reg$alpha_flex, loc_reg$num_flex, lubridate:::.c_parser_reg_flex)
exact_regs <- c(loc_reg$alpha_exact, loc_reg$num_exact, lubridate:::.c_parser_reg_exact)
# the two format chosen in this case
flex_regs[c("b", "Ob")]
#> $b
#> [1] "((?<b_b>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)|(?<B_b>January|February|March|April|May|June|July|August|September|October|November|December))(?![[:alpha:]])"
#> 
#> $Ob
#> [1] "(((?<Ob_b>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)|(?<Ob_B>January|February|March|April|May|June|July|August|September|October|November|December))(?![[:alpha:]]))"
exact_regs[c("b", "Ob")]
#> $b
#> [1] "((?<b_b_e>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)|(?<B_b_e>January|February|March|April|May|June|July|August|September|October|November|December))(?![[:alpha:]])"
#> 
#> $Ob
#> [1] "(((?<Ob_b_e>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)|(?<Ob_B_e>January|February|March|April|May|June|July|August|September|October|November|December))(?![[:alpha:]]))"
```

In each, there is a negative lookhead group construct `(?![[:alpha:]])`. I think this is what prevents `Sept` to be matched.
The correct abbreviation for lubridate is `Sep`, and `Sep.` is matched because not in `[[:alpha:]]`.
Either the regex needs to evolve or in the locale _English\_United States.1252_, `Sept` is not a correct abreviation and lubridate is ok. 
Also, `parse_date_time2` is working because I think it is another mechanism in C code.

Hope it helps

**Comment by vspinu** [comment]
You are right. Indeed. The guessing works by retrieving the locale abbreviations for `b`. It hardly could be anything else because it needs to work for all locales. The internal parser is targeted for English and thus any abbreviation works. 

I would rather leave this as it is in order to avoid further complication of already complicated code.  Workaround is always to either gsub Sept into Sep, or use internal parser directly through `parse_date_time2`.

**Comment by cderv** [comment]
I agree with you completely to leave as is. I think it is to the user to use the correct locale abbreviation, and process with `gsub` if needed
I'll just add that month abbreviation can be different by locales. I know that in French, it would be `Sept.` with a `.`. There may be a local where `Sept` is the correct abbreviation... don't know if it could help @metanoid as I don't know how to find one.
