### ISSUE TITLE
Incorrect DST ending hour

### ISSUE THREAD

**Issue by abekhit** [tidyverse/lubridate#948]
Lubridate switches from DST to EST at 1 AM instead of 2 AM. Also` ymd_hms("2019-11-03 02:00:00",tz = "America/New_York")` should return two timestamps: one with EST and one with DST. Related to #145 

```r
library(lubridate)

# 1 AM on Nov 11 is DST Not EST
ymd_hms("2019-11-03 01:00:00",tz = "America/New_York")
#> [1] "2019-11-03 01:00:00 EST"

# same issue when displaying time as UTC
with_tz(ymd_hm("2019-11-03 00:00",tz = "America/New_York"),"UTC")
#> [1] "2019-11-03 04:00:00 UTC"
with_tz(ymd_hm("2019-11-03 01:00",tz = "America/New_York"),"UTC")
#> [1] "2019-11-03 06:00:00 UTC"

# converting UTC to America/NY shows that the change from DST to EST occur at 1 AM when it should occur at 2 AM 
with_tz(ymd_hms("2019-11-03 05:00:00", tz = "UTC"),"America/New_York")
#> [1] "2019-11-03 01:00:00 EDT"
with_tz(ymd_hms("2019-11-03 06:00:00", tz = "UTC"),"America/New_York")
#> [1] "2019-11-03 01:00:00 EST"
```

**Comment by vspinu** [comment]
> should return two timestamps: one with EST and one with DST.

Unfortunately for repeated time-dates there is no control currently which date it is, so the latter is assumed. R doesn't allow two time-zones per vector, so what you are asking is not possible. 

> Lubridate switches from DST to EST at 1 AM instead of 2 AM. 

The roll back 1 h happens at 2AM and 2AM DST, becomes 1AM EST. The behavior is as expected. 

```
> with_tz(ymd_hms("2019-11-03 05:01:01", tz = "UTC"),"America/New_York")
[1] "2019-11-03 01:01:01 EDT"
> with_tz(ymd_hms("2019-11-03 06:01:01", tz = "UTC"),"America/New_York")
[1] "2019-11-03 01:01:01 EST"
```

> # same issue when displaying time as UTC

Same as before, for repeated time the latter event is assumed. Maybe in the future when we have time zone parsing this could be fixed by parsing EST, DST labels, if you have those. But in your examples it looks like you don't.

```
> with_tz(ymd_hm("2019-11-03 00:59", tz = "America/New_York"),"UTC")
[1] "2019-11-03 04:59:00 UTC"
> with_tz(ymd_hm("2019-11-03 01:00", tz = "America/New_York"),"UTC")
[1] "2019-11-03 06:00:00 UTC"
> with_tz(ymd_hm("2019-11-03 02:00", tz = "America/New_York"),"UTC")
[1] "2019-11-03 07:00:00 UTC"
```
