### ISSUE TITLE
Version mismatch between CRAN and the website and changelog

### ISSUE THREAD

**Issue by averiperny** [tidyverse/lubridate#981]
CRAN and says version 1.7.10 but the website says 1.7.9.9000 and the changelog is missing 1.7.10 info.
![image](https://user-images.githubusercontent.com/17169253/126014948-42c75555-1fef-4c64-bb5b-9b6e7ac09b58.png)
![image](https://user-images.githubusercontent.com/17169253/126015126-177100f8-6ba0-4cf9-8070-4b9675ec3a67.png)

Similar to this issue on dplyr tidyverse/dplyr#5948?

**Comment by vspinu** [comment]
The pkgbuild was failing. I fixed it but the problem still persists. I do see the website being pushed correctly to the gh-pages branch (429f9f4), but somehow it's not propagated to the actual github page (https://lubridate.tidyverse.org/). Let's wait a bit. Maybe it solves by itself.

**Comment by vspinu** [comment]
@DavisVaughan would you mind having a look at this one? Or who can I ask to help with this? The pkgdown action runs correctly but the website is not propagated:

   https://github.com/tidyverse/lubridate/actions/workflows/pkgdown-pak.yaml
   https://lubridate.tidyverse.org/

**Comment by DavisVaughan** [comment]
The "auto" development mode that is set [here](https://github.com/tidyverse/lubridate/blob/c2e4c1d994eaad7a921fc89d503d1bdc1d73ea05/_pkgdown.yml#L6) will push the docs to the normal release site when the package version number is a non-dev version (i.e. it doesn't contain the `.9000` bit). Otherwise, it will push the docs to `/dev` on the site.

You can see the dev site is here, which has the right version number https://lubridate.tidyverse.org/dev/

Read more about this in the Development Mode section of `?pkgdown::build_site()`

When you do the next release, just make sure that you make a commit to master while the package has a version of `1.7.11`. That should update the normal non-dev site (as long as the pkgdown workflow passes). Then you can bump the version to the development version for continued development.

**Comment by vspinu** [comment]
Got it. Makes sense indeed. Pkgdown workflow was broken back in March. This explains why it skipped the updates to the released version.

Thanks!!!
